name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Perform tests
        run: |
          sudo apt update && sudo apt-get -y install build-essential cmake wget clang
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
          tar -xvf premake-5.0.0-alpha15-linux.tar.gz
          mkdir bin
          cp premake5 bin/premake5
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin
          cd dev
          ./test.sh
